# Generated by Django 2.2.7 on 2019-11-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('directors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('films_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('running_time', models.IntegerField()),
                ('release_date', models.DateField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directors.Director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genres.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Starring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actors.Actor')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movie')),
            ],
        ),
    ]
