# Generated by Django 2.2.7 on 2019-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starring',
            name='character_name',
            field=models.CharField(default='random character', max_length=200),
        ),
    ]
