# Generated by Django 2.2.7 on 2019-11-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_starring_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='films_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
